#!/usr/bin/env python3
"""gen_layout.py — turn a Visual6502-style segdefs into a slim browser layout file.

Emits <chip>_layout.js:  var LAYOUT = { chip, bbox, chipSize, layers, segs, names }
  segs  = [ [node, layer, x1,y1, x2,y2, ...], ... ]   (the pull char is dropped;
          coordinates rounded to int — die coords are already integer-ish)
  names = { "<id>": "<primary name>", ... }            (for the click tooltip)

die-viewer.js renders these polygons live (canvas, CSS zoom/pan, hit buffer),
so the per-mechanism highlight files only need node-id lists — the polygons are
already here.

Netlist provenance: use the CORRECTED data/system-def/ netlist (raw upstream
2A03 dropped t13032b + t14634b). The segdefs DATA is CC-BY-NC-SA (Visual
2A03/2C02 / Visual6502) — this file inherits that licence; keep attribution.

Usage:
  python gen_layout.py --segdefs .../2c02/segdefs.js --nodenames .../2c02/nodenames.js \
      --chip 2C02 --out 2c02_layout.js
Stdlib only.
"""
import argparse, os, re, sys, gzip, json
from collections import defaultdict


def parse_nodenames(path):
    id_to_name = {}
    txt = open(path, encoding="utf-8", errors="replace").read()
    # name : id   (keep the FIRST short/clean name per id for the tooltip)
    for m in re.finditer(r"['\"]?([\w/#~+.\-\[\]]+)['\"]?\s*:\s*(\d+)", txt):
        nm, nid = m.group(1), int(m.group(2))
        if nid not in id_to_name or len(nm) < len(id_to_name[nid]):
            id_to_name[nid] = nm
    return id_to_name


def parse_segdefs(path):
    """Each entry: [node, 'pull', layer, x1,y1, x2,y2, ...]. Return [(node, layer, [coords])]."""
    txt = open(path, encoding="utf-8", errors="replace").read()
    segs = []
    # match one bracketed row: node , 'pull' , layer , <coord csv>
    row = re.compile(r"\[\s*(\d+)\s*,\s*'[+-]'\s*,\s*(\d+)\s*,\s*([-\d,\s]+?)\]")
    for m in row.finditer(txt):
        node = int(m.group(1)); layer = int(m.group(2))
        coords = [int(round(float(c))) for c in m.group(3).split(",") if c.strip()]
        if len(coords) >= 6:          # need >=3 vertices for a polygon
            segs.append((node, layer, coords))
    return segs


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--segdefs", required=True)
    ap.add_argument("--nodenames", required=True)
    ap.add_argument("--chip", default="chip")
    ap.add_argument("--out", required=True)
    a = ap.parse_args()

    segs = parse_segdefs(a.segdefs)
    if not segs:
        sys.exit("no segments parsed — check the segdefs path/format")
    names = parse_nodenames(a.nodenames)

    xs = []; ys = []; layers = set()
    for _, layer, c in segs:
        layers.add(layer); xs += c[0::2]; ys += c[1::2]
    minx, maxx, miny, maxy = min(xs), max(xs), min(ys), max(ys)
    chip_size = max(maxx - minx, maxy - miny)

    # only ship names for nodes that actually appear in segs (tooltip surface)
    seg_nodes = {n for n, _, _ in segs}
    names = {str(nid): nm for nid, nm in names.items() if nid in seg_nodes}

    # compact JSON arrays (no spaces) keep the file small; GitHub Pages gzips on the wire
    seg_js = "[" + ",".join(
        "[" + str(n) + "," + str(l) + "," + ",".join(map(str, c)) + "]" for n, l, c in segs) + "]"
    obj = (
        "// AprVisual S1a — die layout data (generated by gen_layout.py). Do not edit by hand.\n"
        "// Source netlist: Visual %s (corrected data/system-def). Data licence: CC-BY-NC-SA.\n"
        "var LAYOUT = {chip:%s,bbox:[%d,%d,%d,%d],chipSize:%d,layers:%d,\n"
        "names:%s,\nsegs:%s};\n"
    ) % (a.chip, json.dumps(a.chip), minx, miny, maxx, maxy, chip_size, max(layers) + 1,
         json.dumps(names, ensure_ascii=False, separators=(",", ":")), seg_js)

    os.makedirs(os.path.dirname(os.path.abspath(a.out)), exist_ok=True)
    open(a.out, "w", encoding="utf-8").write(obj)

    raw = len(obj.encode("utf-8"))
    gz = len(gzip.compress(obj.encode("utf-8"), 9))
    print(f"[{a.chip}] {len(segs):,} segs, {len(seg_nodes):,} nodes, {len(layers)} layers, "
          f"bbox=({minx},{miny})-({maxx},{maxy})")
    print(f"  wrote {a.out}: raw {raw/1e6:.2f} MB, gzipped {gz/1e6:.2f} MB (over-the-wire)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
